blog/urls.py
from django.urls import path 
from . import views

app_name ="blog"

urlpatterns = [
    path('' , views.index , name ="index"),
    #path('posts/' , views.post_list , name = "post_list"),
    path('posts/' , views.PostListView.as_view() , name = "post_list"),
    path('posts/<pk>/' , views.post_detail , name = "post_details"),
    path('posts/<post_id>/comment' , views.post_comment , name = "post_comment"),
    path('ticket' , views.ticket , name = "ticket"),

]

project/urls.py
from django.contrib import admin
from django.urls import include,path

urlpatterns = [
    path('admin/', admin.site.urls),
    path('blog/' , include('blog.urls' , namespace = "blog")),
]

blog/models.py
from django.db import models
from django.utils import timezone 
from django.contrib.auth.models import User
from django.urls import reverse

# manager 
class PublishedManager(models.Manager) :
    def get_queryset(self) :
        return super().get_queryset().filter(status = Post.Status.PUBLISHED)

# Create your models here.
class Post(models.Model) :
   
    #relational
    author = models.ForeignKey(User , on_delete =models.CASCADE ,related_name = 'user_posts',verbose_name="نویسنده")
    class Status(models.TextChoices) :
        DRAFT = 'DR' , 'Draft'
        PUBLISHED = 'PB' ,'published'
        REJECTED =  'RJ' , 'rejected'
        
    #data fields
    title = models.CharField(max_length=250,verbose_name="عنوان")
    description = models.TextField(verbose_name="توضیحات ")
    slug = models.SlugField(max_length=250,verbose_name="اسلاگ")
    
    #date 
    publish = models.DateTimeField(default=timezone.now,verbose_name="تاریخ انتشار")
    created = models.DateTimeField(auto_now_add=True)
    updated = models.DateTimeField(auto_now=True)
    
    objects = models.Manager()
    published = PublishedManager()
    #choice fields
    status = models.CharField(max_length = 2 , choices=Status.choices , default=Status.DRAFT,verbose_name="وضعیت" )
    reading_time = models.PositiveIntegerField(verbose_name = "زمان مطالعه ")
    
    class Meta :
        ordering = ['-publish']
        indexes = [
            models.Index(fields = ['-publish'])
        ]
        verbose_name="پست"
        verbose_name_plural="پست ها"
    def __str__ (self) :
        return self.title

    def get_absolute_url(self):
        return reverse("blog:post_details" , args=[self.id])
    
class Ticket(models.Model):
    message = models.TextField(verbose_name ="پیام ")
    name = models.CharField(max_length=250, verbose_name = "نام")
    email = models.EmailField(verbose_name = "ایمیل")
    phone = models.CharField(max_length=11, verbose_name = "شماره تماس")
    subject = models.CharField(max_length=250, verbose_name = "موضوع")
    class Meta :
        verbose_name="تیکت"
        verbose_name_plural="تیکت ها" 

    def __str__ (self) :
        return self.name 

class Comment(models.Model):
    post = models.ForeignKey(Post,on_delete=models.CASCADE,related_name = 'comments',verbose_name="پست") 
    name = models.CharField(max_length=150, verbose_name="نام و نام خانوادگی")
    body = models.CharField(max_length=500,verbose_name="بدنه پیام")
    created = models.DateTimeField(auto_now_add=True, verbose_name="تاریخ انتشار")
    updated = models.DateTimeField(auto_now=True, verbose_name="تاریخ ویرایش")
    active = models.BooleanField(default=False,verbose_name= "وضعیت")

    class Meta :
        ordering = ['-created']
        indexes = [
            models.Index(fields = ['-created'])
        ]
        verbose_name="کامنت"
        verbose_name_plural="کامنت ها"
        
    def __str__ (self) :
        return f"{self.name}:{self.post}"

blog/forms.py
from django import forms
from .models import Comment

class TicketForm(forms.Form):
    SUBJECT_CHOICES =(
        ('پیشنهاد','پیشنهاد'),
        ('انتقاد','انتقاد'),
        ('گزارش','گزارش')
    )
    message = forms.CharField(widget=forms.Textarea, required=True)
    name = forms.CharField(max_length=250, required=True , widget=forms.TextInput(attrs={'placeholder':'نام',
                                                                                'style':'height:30px','class':'name'}))
    email = forms.EmailField()
    phone = forms.CharField(max_length=11, required=True)
    subject = forms.ChoiceField(choices=SUBJECT_CHOICES)

    def clean_phone(self):
        phone =self.cleaned_data['phone']
        if phone:
            if not phone.isnumeric() :
                raise forms.ValidationError("شماره تلفن عددی نیست")
            else: 
                return phone

class CommentForm(forms.ModelForm):
    def clean_name(self):
        name = self.cleaned_data['name']
        if name:
            if len(name)<3 :
                raise forms.ValidationError("نام کوتاه است!")
            else: 
                return name
    class Meta:
        model = Comment
        fields = ['name','body']
        

blog/views.py
from django.shortcuts import render , get_object_or_404,redirect 
from django.http import HttpResponse , Http404
from .models import *
from .forms import *
from django.core.paginator import Paginator, EmptyPage,PageNotAnInteger
from django.views.generic import ListView,DetailView
from django.views.decorators.http import require_POST
# Create your views here. 

def index (request) : 
    return render(request,'blog/index.html')



#def post_list(request):
 #   posts = Post.published.all() 
  #  paginator = Paginator(posts, 3)
   # page_number = request.GET.get('page',1)
    #try:
     #   posts = paginator.page(page_number)
    #except EmptyPage:
     #   posts = paginator.page(paginator.num_pages)
    #except PageNotAnInteger:
     #   posts = paginator.page(1)
    #context ={
     #   'posts' : posts ,
    #}

   # return render(request ,"blog/list.html",context)

class PostListView(ListView):
    queryset = Post.published.all()
    context_object_name = "posts"
    paginate_by = 3 
    template_name = "blog/list.html"

def post_detail(request, pk):
    post = get_object_or_404(Post , id=pk , status=Post.Status.PUBLISHED)
    form = CommentForm()
    comments = post.comments.filter(active = True)
    context = {
        'post': post,
        'form' : form, 
        'comments' : comments,
    }
    return render(request,"blog/detail.html", context)
    
#class PostDetailView(DetailView) :
 #   model= Post
  #  template_name = "blog/detail.html"

def ticket(request):
    if request.method == "POST":
        form = TicketForm(request.POST)
        if form.is_valid():
            ticket_obj = Ticket.objects.create(message=cd["message"],name=cd["name"],
                                               email=cd["email"],phone=cd["phone"],subject=cd["subject"])
            cd = form.cleaned_data
            ticket_obj.save() 
            return redirect("blog:ticket")
    else:
        form = TicketForm()
    return render(request , "forms/ticket.html" , {"form":form})

@require_POST
def post_comment(request , post_id) :
    post = get_object_or_404(Post, id=post_id, status = Post.Status.PUBLISHED)
    comment = None
    form = CommentForm(data = request.POST)
    if form.is_valid():
        comment = form.save(commit = False)
        comment.post = post
        comment.save()
    context={ 
        'post' : post,
        'form' : form,
        'comment' : comment,
        }
    return render(request,"forms/comment.html",context)

blog/templates/blog/detail.html
{% extends 'parent/base.html'%}
{%block title %} post details {%endblock%}
{% block content %} 
    <h1>post details</h1>
    <h2>{{ post.title }} (by {{ post.author }})</h2>
    <p>{{ post.description }}</p>
    <hr>
   <p>{{ post.publish }}</p> 

   <div>
    {%with comments.count as cm_count %}
    {{cm_count}}comment{{cm_count|pluralize}}
   </div>

   <div>
    {%for cm in comments%}
        {{cm.body|linebreaks}}
        <br>
        {{cm.name}}
    {%empty%} 
        کامنتی وجود ندارد!
    {% endfor %}
   </div>
   {% endwith %}
   <form method = "post"action ="{% url 'blog:post_comment' post.id %}">
        {% csrf_token %}
        {{form.as_p}} 
        <input type = "submit" value = " افزودن کامنت">
    </form>
{%endblock %} 

blog/templates/blog/index.html
{% extends 'parent/base.html'%}
{%load blog_tags%}
{%block title %} post list {%endblock%}
{% block content %} 
    <h1>آمار</h1>
    <p>{%total_posts%}:تعدادپست ها</p>
    <p>{%total_comments%}:تعداد کامنت ها</p>
    <p>{%last_post_date%}:تاریخ آخرین پست</p>

    {% latest_posts 5 %} 

    <h1>محبوبترین پست ها</h1>
    {%most_popular_posts as pop_posts%}
    {%for post in pop_posts%}
        <br>
        <a href="{{post.get_absolute_url}}">{{post.title}}: with {{post.comments_count}}comments</a>
    {% endfor %}
{%endblock %} 

blog/templates/blog/list.html
{% extends 'parent/base.html'%}
{%block title %} post list {%endblock%}
{% block content %} 
<h1>لیست پست ها</h1>
    <ol style="--length: {{posts|length}}" role="list">
        {% for post in posts %}
        <li style="--i: {{forloop.counter}}">    
        <h3>
                <a href=" {{post.get_absolute_url}}"> {{post.title}} </a> 
        </h3>
        
            <p>{{post.description | truncatewords:5}} </p>
        </li>
        {% endfor %}
    </ol>
    
    {% include "partials/pagination.html" with page=page_obj %}
{%endblock %} 

blog/templates/forms/comment.html
{% extends 'parent/base.html'%}
{%block title %} post comment {%endblock%}
{% block content %} 
    {%if comment%}
        کامت شما با موفقیت ثبت شد. 
        <a href = "{{post.get_absolute_url}}">بازگشت به پست </a>
    {% else %}
    <form method = "post" >
        {% csrf_token %}
        {{form.as_p}} 
        <input type = "submit" value = " افزودن کامنت">
    </form>
    {% endif %}
{%endblock %} 

blog/templates/forms/ticket.html
{% extends 'parent/base.html'%}
{%block title %} Ticket form {%endblock%}
{% block content %} 
<h1> ارسال تیکت </h1>
    <form method = "post">
    {% csrf_token %}
    
    {{ form.as_p }}
    <input type = "submit" , value = "ثبت تیکت">
    </form>
    {%if forms.errors%}
        لطفا خطای زیر را اصلاح کنید!
        <br>
        {%for field in form%}
            {%if field.errors%} 
                {%for error in field.errors%}
                    {{field.label}} : {{error}}
                {%endfor%}
            {%endif%}
        {%endfor%}
    {%endif%}
    {%if form.none_field_errors%}
        {{form.none_field_errors}}
    {%endif%}
{%endblock %} 

blog/templates/parent/base.html
{% load static %}
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <title>blog|{% block title %} {% endblock %}</Title> 
    <link rel = "stylesheet" type="text/css" href="{%static 'css/base.css '%}"> 
    {% block head %} 
    
    {% endblock %}

</head>
<body>
{%include 'partials/header.html'%}
{%include 'partials/navigation.html'%}
{% block content %} {%endblock %}
{%include 'partials/footer.html'%}    
</body>
</html> 

blog/templates/partials/latest_posts.html
<div>
    <h1>آخرین پست ها</h1>
    {%for post in l_posts%}
        <a href="{{ post.get_absolute_url }}">{{post.title}}</a>
    {%endfor%}
</div>

blog/templates/partials/pagination.html
<div class="pagination">
{% if page_obj.has_previous %}
  <a href="?page={{ page_obj.previous_page_number }}">« Previous page</a>

  {% if page_obj.number > 3 %}
    <a href="?page=1">1</a>
    {% if page_obj.number > 4 %}
      <span>...</span>
    {% endif %}
  {% endif %}
{% endif %}

{% for num in page_obj.paginator.page_range %}
  {% if page_obj.number == num %}
    <a href="?page={{ num }}">{{ num }}</a>
  {% elif num > page_obj.number|add:'-3' and num < page_obj.number|add:'3' %}
    <a href="?page={{ num }}">{{ num }}</a>
  {% endif %}
{% endfor %}

{% if page_obj.has_next %}
  {% if page_obj.number < page_obj.paginator.num_pages|add:'-3' %}
    <span>...</span>
    <a href="?page={{ page_obj.paginator.num_pages }}">{{ page_obj.paginator.num_pages }}</a>
  {% elif page_obj.number < page_obj.paginator.num_pages|add:'-2' %}
    <a href="?page={{ page_obj.paginator.num_pages }}">{{ page_obj.paginator.num_pages }}</a>
  {% endif %}

  <a href="?page={{ page_obj.next_page_number }}">Next Page »</a>
{% endif %}
</div>